--TEST--
NumPower exp/log family: results match PyTorch / libm reference values
--FILE--
<?php
/* Cross-reference NumPower's CPU and GPU outputs against a fixed,
   bit-exact PyTorch-equivalent reference table.

   Why this matters:
   - PyTorch on CPU calls into libm directly (`expf`/`logf` for float32,
     `exp`/`log` for float64, with a fp32→fp16→fp32 round-trip for
     float16). NumPower's CPU path uses the same libm intrinsics and
     follows the same fp32→fp16 storage path.
   - PyTorch on GPU calls CUDA libdevice (`exp`/`log` etc.); NumPower's
     GPU kernels call those same libdevice intrinsics.
   - On every input we exercise, Python's `math` module (also a libm
     wrapper) produces values that round-trip bit-equivalent to
     `torch.<op>(t.to(dtype))`.

   The reference table below was generated by
   `python3 tools/pytorch_ref.py` (see comment in
   tests/math/109-exp-log-coverage-gaps.phpt). Inputs:
     positive set: [1.0, 2.0, 4.0, 8.0, M_E, M_PI]
     real set:     [0.0, 1.0, -1.0, M_E, -M_E]
   For float16 the values are pre-rounded via fp16 storage so an
   exact-equality compare works on CPU. */

$inputs_pos  = [1.0, 2.0, 4.0, 8.0, M_E, M_PI];
$inputs_real = [0.0, 1.0, -1.0, M_E, -M_E];

/* ─── Reference table (libm = PyTorch CPU == numpower CPU exact path) ──── */
$ref = [
    /* exp(positive) */
    ['exp', $inputs_pos, [
        2.718281828459045, 7.38905609893065, 54.598150033144236, 2980.9579870417283,
        15.154262241479262, 23.140692632779267,
    ]],
    /* exp(real) */
    ['exp', $inputs_real, [
        1.0, 2.718281828459045, 0.36787944117144233,
        15.154262241479262, 0.06598803584531254,
    ]],
    /* exp2(positive) */
    ['exp2', $inputs_pos, [
        2.0, 4.0, 16.0, 256.0,
        6.580885991017885, 8.824977827076287,
    ]],
    /* exp2(real) */
    ['exp2', $inputs_real, [
        1.0, 2.0, 0.5,
        6.580885991017885, 0.151955223188026,
    ]],
    /* expm1(positive) */
    ['expm1', $inputs_pos, [
        1.718281828459045, 6.38905609893065, 53.598150033144236, 2979.9579870417283,
        14.154262241479262, 22.140692632779267,
    ]],
    /* expm1(real) */
    ['expm1', $inputs_real, [
        0.0, 1.718281828459045, -0.6321205588285577,
        14.154262241479262, -0.9340119641546874,
    ]],
    /* log(positive) */
    ['log', $inputs_pos, [
        0.0, 0.6931471805599453, 1.3862943611198906, 2.0794415416798357,
        1.0, 1.1447298858494002,
    ]],
    /* log(real): log(0) = -inf, log(-1) = NaN, log(-M_E) = NaN */
    ['log', $inputs_real, [
        -INF, 0.0, NAN, 1.0, NAN,
    ]],
    /* log1p(positive) */
    ['log1p', $inputs_pos, [
        0.6931471805599453, 1.0986122886681098, 1.6094379124341003, 2.1972245773362196,
        1.3132616875182228, 1.4210804327809621,
    ]],
    /* log1p(real): log1p(-1) = -inf, log1p(-M_E) = NaN */
    ['log1p', $inputs_real, [
        0.0, 0.6931471805599453, -INF,
        1.3132616875182228, NAN,
    ]],
    /* log2(positive) */
    ['log2', $inputs_pos, [
        0.0, 1.0, 2.0, 3.0,
        1.4426950408889634, 1.6514961294723187,
    ]],
    /* log2(real): log2(0) = -inf, log2(<=0) = NaN */
    ['log2', $inputs_real, [
        -INF, 0.0, NAN, 1.4426950408889634, NAN,
    ]],
    /* log10(positive) */
    ['log10', $inputs_pos, [
        0.0, 0.3010299956639812, 0.6020599913279624, 0.9030899869919435,
        0.4342944819032518, 0.4971498726941338,
    ]],
    /* log10(real) */
    ['log10', $inputs_real, [
        -INF, 0.0, NAN, 0.4342944819032518, NAN,
    ]],
    /* logb: floor(log2(|x|)) for normals, ±0 = -Inf, ±Inf = +Inf, NaN preserved */
    ['logb', $inputs_pos, [
        0.0, 1.0, 2.0, 3.0,
        1.0, 1.0,
    ]],
    ['logb', $inputs_real, [
        -INF, 0.0, 0.0,   /* logb(-1) = logb(|-1|) = logb(1) = 0 */
        1.0, 1.0,         /* logb(-e)  = logb(|−e|) = logb(e)  = 1 */
    ]],
];

function approx_one($g, $w, $tol) {
    if (is_nan($w)) return is_nan($g);
    if (is_infinite($w)) return is_infinite($g) && (($g < 0) === ($w < 0));
    if (is_infinite($g)) return false;
    if (is_nan($g)) return false;
    return abs($g - $w) <= max($tol, abs($w) * $tol);
}

function check_table($op, $inputs, $expected, $dtype, $tol, $on_gpu) {
    $arr = NumPower::array($inputs, $dtype);
    if ($on_gpu) $arr = $arr->gpu();
    $got = NumPower::$op($arr);
    $vals = $on_gpu ? $got->cpu()->toArray() : $got->toArray();

    $ok = true;
    foreach ($expected as $i => $w) {
        if (!approx_one($vals[$i], $w, $tol)) {
            $ok = false;
            $tag = $on_gpu ? "GPU" : "CPU";
            echo "FAIL $dtype $op $tag [$i]: expected=", json_encode($w),
                 ", got=", json_encode($vals[$i]),
                 ", input=", $inputs[$i], "\n";
        }
    }
    if ($ok) {
        $tag = $on_gpu ? "GPU" : "CPU";
        echo "OK $dtype $op $tag\n";
    }
}

$tols = [
    'float16' => 5e-3,
    'float32' => 1e-6,
    'float64' => 1e-12,
];

/* CPU coverage on every fp dtype × every op × {positive, real} input */
foreach ($tols as $dt => $tol) {
    foreach ($ref as [$op, $inputs, $expected]) {
        check_table($op, $inputs, $expected, $dt, $tol, false);
    }
}

/* GPU coverage when available */
$gpu_available = false;
try {
    $probe = NumPower::array([1.0])->gpu();
    $gpu_available = $probe->isGPU();
} catch (Throwable $t) {
    echo "skip GPU not available: " . $t->getMessage() . "\n";
}
if ($gpu_available) {
    foreach ($tols as $dt => $tol) {
        foreach ($ref as [$op, $inputs, $expected]) {
            check_table($op, $inputs, $expected, $dt, $tol, true);
        }
    }
}

/* ── fp128 path: cross-reference against fp64 via fp128.toFloat() ─────── */
/* libquadmath / DD on CPU keeps enough precision that the result, cast
   down to fp64, must agree with the libm fp64 result to ~1e-14. */
foreach ([['exp', $inputs_pos], ['log', [1.0, 2.0, M_E, M_E*M_E]]] as [$op, $inputs]) {
    $str_in = array_map(fn($v) => (string)$v, $inputs);
    $r128 = NumPower::$op(NumPower::array($str_in, 'float128'))->toArray();
    $r64  = NumPower::$op(NumPower::array($inputs, 'float64'))->toArray();
    foreach ($inputs as $i => $_) {
        $diff = abs((float)$r128[$i] - $r64[$i]);
        if ($diff <= 1e-13) {
            /* OK quietly */
        } else {
            echo "FAIL fp128 $op[$i] vs fp64: diff=$diff\n";
        }
    }
    echo "OK fp128 $op CPU agrees with fp64\n";
}

echo "DONE\n";
?>
--EXPECTF--
%aDONE
